---
abstract: 'Moose Types for Log::Any'
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  Class::Load: 0.20
  File::Find: 0
  File::Temp: 0
  Moose: 0
  Test::Fatal: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-LogAny
no_index:
  file:
    - perlcritic.rc
provides:
  MooseX::Types::LogAny:
    file: lib/MooseX/Types/LogAny.pm
    version: 0.001001
requires:
  Log::Any: 0
  Log::Any::Adapter: 0
  MooseX::Types: 0
  perl: 5.008
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/xenoterracide/moosex-types-logany/issues
  homepage: https://metacpan.org/release/MooseX-Types-LogAny
  repository: git://github.com/xenoterracide/moosex-types-logany.git
version: 0.001001
